### ISSUE TITLE
April 29, 5-8PM

### ISSUE THREAD

**Issue by kevineder** [lzell/nickel#15]
Hello,

The following date is not parsed correctly "April 29 5-8PM"

I'm having trouble finding where in the code this can be remedied. Would appreciate a patch or any tips.

Here's a test case if that helps:

``` ruby
def test__april_29_5_to_8_pm
    now = Time.local(2008, 11, 30)
    assert_nlp NLP.new("April 29, 5-8pm", now), 
      [Occurrence.new(
        :type => :single, 
        :start_date => ZDate.new("20080429"), 
        :start_time => ZTime.new("5", :pm),
        :end_time => ZTime.new("8", :pm))]

  end
```

**Comment by kevineder** [comment]
Sorry for the unnecessary ticket - I ended up figuring this out. Here is a pull request: https://github.com/lzell/nickel/pull/16

**Comment by lzell** [comment]
Hi Kevin, 

Thank you for the patch!

Lou

**Comment by kevineder** [comment]
Hi Lou,

No problem, thanks for pulling it in!
